dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: openstack
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-redhat_satellite6_storage
provisioner:
  name: ansible
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
    cleanup: ../shared/cleanup.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  # Using the shared directory is useful for sharing tests across scenarios,
  # but is not a requirement. For scenario specific tests, add the appropriate
  # file path to the test or test directory below
  additional_files_or_dirs:
    - ../../shared/tests
lint: |
    yamllint .
    ansible-lint
    flake8
